
trigger:
- master

pool:
  name: 'agent1'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'git clone https://github.com/IntelliqDevops/maven.git'
- task: Bash@3
  inputs:
     targetType: 'inline'
     script: 'cd /home/azureuser/myagent/_work/1/s;mvn package'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo scp /home/azureuser/myagent/_work/1/s/webapp/target/webapp.war ubuntu@54.227.114.61:/var/lib/tomcat10/webapps/test.war'
