# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: imran

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'git clone https://github.com/naeem331134/maven.git'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cd /home/azureuser/myagent/_work/1/s/maven;mvn package'

- script: |
    cat << EOF > dockerfile
    FROM tomee
    COPY webapp.war /usr/local/tomee/webapps/myapp.war
    EOF

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker build -t registery123.azurecr.io/app1 .'